### ISSUE TITLE
Bug: vitals level & class don't update

### ISSUE THREAD

**Issue by iLPdev** [iLPdev/prs#111]
from Rasoul:

> level in the vitals tab doesn't update when char levels up

**Comment by sorenmarkert** [comment]
Sending `gmcp refresh` to the server doesn't fix it

**Comment by sorenmarkert** [comment]
This also affects changing class

**Comment by iLPdev** [comment]
They're both prolly not tied into the 'prs-core.lua' gmcp update event.

**Comment by iLPdev** [comment]
resolved by [#721d7e1](https://github.com/iLPdev/prs/commit/721d7e6349c6ebdb8ac48808f49301453a6af684) and [#0297e1a](https://github.com/iLPdev/prs/commit/0297e1aab632e3233213e91a64650eb299ca95ed)
