### ISSUE TITLE
PRS logo

### ISSUE THREAD

**Issue by iLPdev** [iLPdev/prs#87]
we need a logo

**Comment by H4RV3Y2805** [comment]
![logo-no-background](https://github.com/iLPdev/prs/assets/8833420/c844e038-6dd8-43da-8d70-0d6d977c80ba)
I went on a logo making site and came up with this. Maybe helpful, maybe trash. Just thought I'd do what I could to help.

**Comment by iLPdev** [comment]
@all-contributors please add @H4RV3Y2805 for design
