### ISSUE TITLE
Enhancement Request: Minimap Window

### ISSUE THREAD

**Issue by H4RV3Y2805** [iLPdev/prs#90]
Hello, please may I request a Minimap window that I can dock to the left side of the map and chat block. Could it also be sizable similar to this screenshot: https://cdn.discordapp.com/attachments/1029785642818879529/1091971321086349383/Screenshot_20221101_065201.png

**Comment by iLPdev** [comment]
maybe we can convert this "wilderness mapper" (https://forums.mudlet.org/viewtopic.php?f=9&t=3184&p=15240&hilit=wilderness#p15240) to geyser and add it as an adjustable container.

**Comment by iLPdev** [comment]
#137 adds the full ascii map from `map` command... so, related to this issue but not the nearest view of the territory yet.

**Comment by iLPdev** [comment]
added by @grrtt49 in #137
